apiVersion: alloydbomni.dbadmin.goog/v1
kind: DBCluster
metadata:
  name: alloydb-scalardb-cluster
  namespace: default
spec:
  databaseVersion: "17.5.0"
  primarySpec:
    adminUser:
      passwordRef:
        name: db-pw-alloydb-scalardb-cluster
    resources:
      cpu: 1
      memory: 2Gi
      disks:
        - name: DataDisk
          size: 8Gi

  allowExternalIncomingTraffic: true
